server:
  port: 8081

rabbit:
  host: "localhost"
  queue:
    - name: "poc-direct-1"
    - name: "poc-direct-2"
    - name: "poc-topic-1"
    - name: "poc-topic-2"
    - name: "poc-topic-3"
    - name: "poc-fanout-1"
    - name: "poc-fanout-2"
    - name: "poc-fanout-3"
    - name: "poc-header-1"
    - name: "poc-header-2"
    - name: "poc-header-3"