server:
  port: 8080

rabbit:
  host: "localhost"
  exchange:
    - name: "poc-direct"
      type: DIRECT
      binding:
        - queueName: "poc-direct-1"
          routingKey: "route1"
        - queueName: "poc-direct-2"
          routingKey: "route2"
    - name: "poc-topic"
      type: TOPIC
      binding:
        - queueName: "poc-topic-1"
          routingKey: "users.#"
        - queueName: "poc-topic-2"
          routingKey: "users.*"
        - queueName: "poc-topic-3"
          routingKey: "users.update"
    - name: "poc-fanout"
      type: FANOUT
      binding:
        - queueName: "poc-fanout-1"
        - queueName: "poc-fanout-2"
        - queueName: "poc-fanout-3"
    - name: "poc-header"
      type: HEADERS
      binding:
        - queueName: "poc-header-1"
          headers:
            header11: value11
            header12: value12
            header13: value13
        - queueName: "poc-header-2"
          headers:
            header21: value21
            header22: value22
            header23: value23
        - queueName: "poc-header-3"
          headers:
            header31: value31
            header32: value32
            header33: value33