server:
  port: 8080

rabbit:
  host: "localhost"
  queue:
    - name: "direct-test-1"
    - name: "direct-test-2"
    - name: "topic-test-1"
    - name: "topic-test-2"
    - name: "topic-test-3"
    - name: "fanout-test-1"
    - name: "fanout-test-2"
    - name: "fanout-test-3"
    - name: "header-test-1"
    - name: "header-test-2"
    - name: "header-test-3"
  exchange:
    - name: "direct-test"
      type: DIRECT
      binding:
        - queueName: "direct-test-1"
          routingKey: "route1"
        - queueName: "direct-test-2"
          routingKey: "route2"
    - name: "topic-test"
      type: TOPIC
      binding:
        - queueName: "topic-test-1"
          routingKey: "users.#"
        - queueName: "topic-test-2"
          routingKey: "users.*"
        - queueName: "topic-test-3"
          routingKey: "users.update"
    - name: "fanout-test"
      type: FANOUT
      binding:
        - queueName: "fanout-test-1"
        - queueName: "fanout-test-2"
        - queueName: "fanout-test-3"
    - name: "header-test"
      type: HEADERS
      binding:
        - queueName: "header-test-1"
          headers:
            header11: value11
            header12: value12
            header13: value13
        - queueName: "header-test-2"
          headers:
            header21: value21
            header22: value22
            header23: value23
        - queueName: "header-test-3"
          headers:
            header31: value31
            header32: value32
            header33: value33